- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart kube-apiserver service 
  ansible.builtin.systemd:
    name:  kube-apiserver
    state: restarted
    daemon_reload: true


- name: Restart kube-controller-manager service 
  ansible.builtin.systemd:
    name:  kube-controller-manager
    state: restarted
    daemon_reload: true

- name: Restart kube-scheduler service 
  ansible.builtin.systemd:
    name:  kube-scheduler
    state: restarted
    daemon_reload: true

