apiVersion: v1
kind: Service
metadata:
 name: solar-sys-app
spec:
  type: NodePort
  ports:
    - name: web-port
      port: 3000
      targetPort: 3000
      nodePort: 30000
      protocol: TCP
  selector:
     app: solar-sys-app
      
