- name: Create or update Kubernetes yum repo file
  ansible.builtin.copy:
    dest: /etc/yum.repos.d/kubernetes.repo
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl="https://pkgs.k8s.io/core:/stable:/{{ repo_ver }}/rpm/"
      enabled=1
      gpgcheck=1
      gpgkey=https://pkgs.k8s.io/core:/stable:/{ repo_ver }}/rpm/repodata/repomd.xml.key      
    owner: root
    group: root
    mode: '0644'

- name: Add Docker repo for containerd
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '0644'

- name: Refresh yum cache
  ansible.builtin.command:
    cmd: dnf makecache
  changed_when: false

- name: Install required packages for repo and HTTPS transport
  ansible.builtin.yum:
    name:
      - curl
      - ca-certificates
      - gnupg2
      - dnf-plugins-core
    state: present

- name: Install python3-pip
  package:
    name: python3-pip
    state: present

- name: Install cryptography python library
  pip:
    name: cryptography
    executable: pip3

- name: Disable swap immediately
  ansible.builtin.command: swapoff -a

- name: Remove swap entry from /etc/fstab to disable swap on reboot
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^\s*([^#]\S*\s+)\s+swap\s+(\S+\s+){2}\S+'
    replace: '# \0'

- name: Load required kernel modules
  ansible.builtin.copy:
    src: templates/k8s_modules_load.conf.j2
    dest: /etc/modules-load.d/k8s.conf
    owner: root
    group: root
    mode: '0644'

- name: Ensure kernel modules are loaded
  ansible.builtin.shell: modprobe {{ item }}
  loop:
    - overlay
    - br_netfilter

- name: Apply sysctl params for Kubernetes networking
  ansible.builtin.copy:
    src: templates/k8s_sysctl.conf.j2
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: '0644'

- name: Reload sysctl params
  ansible.builtin.command: sysctl --system 
