---
firewalld_zone: public
firewalld_state: started
firewalld_enabled: true
firewalld_masquerade: disabled
firewalld_ports_udp: []
firewalld_ports_tcp:
  - 6443
  - 179
  - 2379
  - 2380
  - 9090
  - 3000
  - 10250
  - 10251
  - 10252

