- name: Reload systemd
  become: yes
  shell: |
     systemctl daemon-reload
     systemctl daemon-reexec
  
- name: Restart Jenkins
  become: yes
  systemd:
    name: jenkins
    state: restarted
  ignore_errors: yes
  
