- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Restart Node Exporter
  systemd:
    name: node_exporter
    enabled: yes
    state: restarted

- name: Restart Promtail
  systemd:
    name: promtail
    enabled: yes
    state: restarted
