- name: Restart kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: restarted

- name: Restart kube-proxy
  ansible.builtin.systemd:
    name: kube-proxy
    state: restarted

- name: Restart kube-controller-manager
  ansible.builtin.systemd:
    name: kube-controller-manager
    state: restarted

- name: Restart kube-scheduler
  ansible.builtin.systemd:
    name: kube-scheduler
    state: restarted
