pipeline {
    agent any

    tools {
        nodejs 'nodejs-24.1.0'
    }

    stages {
        stage('Installing Dependencies') {
            steps {
                dir('solar-system-demo') {
                    sh 'npm install --no-audit'
                }
            }
        }

        stage('OWASP Dependency Check') {
            steps {
                dependencyCheck additionalArguments: '''
                    --scan ./solar-system-demo
                    --out ./solar-system-demo
                    --format ALL
                    --prettyPrint
                    --failOnCVSS 7.0
                ''', odcInstallation: 'OWASP-DepCheck-12'
            }
        }
    }
}
}
