- name: "Install Kubernetes components in controlplane node"
  hosts: k8sworker
  become: yes
  roles:
    - centos_repo
    - ca_cert
    - prerequisites
    - container_runtime
    - kub_firewall
    - kube_proxy
    - kubelet
    
