apiVersion: v1
kind: Namespace
metadata:
   name: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-kubelet
  namespace: monitoring

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-kubelet
rules:
  - apiGroups: [""]
    resources:
      - nodes/metrics
      - nodes/proxy
      - nodes/stats
      - nodes
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - nodes/metrics/proxy
      - nodes/metrics
    verbs: ["get"]
  - apiGroups: [""]
    resources:
      - endpoints
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-kubelet
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-kubelet
subjects:
  - kind: ServiceAccount
    name: prometheus-kubelet
    namespace: monitoring
